name: VanilifeCore
main: net.azisaba.vanilife.core.VanilifeCore
version: @VERSION@
commands:
  toggleadmin:
    permission: vanilifecore.toggleadmin
  vanilife:
    permission: vanilifecore.vanilife
  book:
    description: 本を入手
