name: VanilifeCore
main: net.azisaba.vanilife.core.VanilifeCore
version: @VERSION@
commands:
  toggleadmin:
    permission: vanilifecore.toggleadmin
  vanilife:
    permission: vanilifecore.vanilife
  book:
    description: 本を入手
  damagenearby:
    permission: vanilifecore.damagenearby
  adminchat:
    permission: vanilifecore.adminchat
permissions:
  vanilifecore.toggleadmin:
    default: false
  vanilifecore.vanilife:
    default: false
  vanilifecore.damagenearby:
    default: false
  vanilifecore.adminchat:
    default: false
    children:
      - vanilifecore.adminchat.listen
  vanilifecore.adminchat.listen:
    default: false
